### ISSUE TITLE
Matrix is singular error in BigWarpExporter

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#107]
Hi  @bogovicj,

I got this error recently, just by moving within a BigDataViewer window which contains a `Warped` source:

```
Exception in thread "PainterThread" java.lang.RuntimeException: Matrix is singular.
	at net.imglib2.realtransform.AffineTransform3D.invert(AffineTransform3D.java:362)
	at net.imglib2.realtransform.AffineTransform3D.set(AffineTransform3D.java:965)
	at bigwarp.BigWarpExporter.estimateAffineFromCorners(BigWarpExporter.java:620)
	at bdv.img.WarpedSource.estimateBoundingInterval(WarpedSource.java:105)
	at bdv.img.WarpedSource.getSource(WarpedSource.java:94)
	at bdv.viewer.render.ProjectorFactory.getTransformedSource(ProjectorFactory.java:281)
	at bdv.viewer.render.ProjectorFactory.createSingleSourceProjector(ProjectorFactory.java:213)
	at bdv.viewer.render.ProjectorFactory.createProjector(ProjectorFactory.java:182)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:628)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:465)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:439)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:473)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
```

This error comes again from the `AffineTransform::set` method which inverts the matrix for each value being set.

These lines : https://github.com/saalfeldlab/bigwarp/blob/62a14af723242ce91d93789547d4499cb2baa6a0/src/main/java/bigwarp/BigWarpExporter.java#L608-L614 need to be replaced by avoiding the set method

**Comment by bogovicj** [comment]
Thanks for the catch @NicoKiaru !
