### ISSUE TITLE
export with FOV specified by landmarks fails in 2d

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/bigwarp#108]
```
Exception in thread "Thread-16" java.lang.ArrayIndexOutOfBoundsException: 3
	at net.imglib2.view.ViewTransforms.permute(ViewTransforms.java:119)
	at net.imglib2.view.Views.permute(Views.java:445)
	at bigwarp.BigWarpARGBExporter.copyToImageStack(BigWarpARGBExporter.java:174)
	at bigwarp.BigWarpARGBExporter.export(BigWarpARGBExporter.java:116)
	at bigwarp.BigWarpExporter$ExportThread.run(BigWarpExporter.java:720)
```

**Comment by bogovicj** [comment]
Possibly related:
```
Exception in thread "Thread-12" java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.realtransform.Wrapped2DTransformAs3D.applyInverse(Wrapped2DTransformAs3D.java:74)
	at bigwarp.landmarks.LandmarkTableModel.computeWarpedPoint(LandmarkTableModel.java:820)
	at bigwarp.landmarks.LandmarkTableModel.updateAllWarpedPoints(LandmarkTableModel.java:790)
	at bigwarp.BigWarp$SolveThread.run(BigWarp.java:3476)

```
