### ISSUE TITLE
BigWarpExporter singular matrix error

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#124]
Hi @bogovicj , 

Rarely, but sometimes, I get this error when moving in Bdv with Warped Sources:

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Matrix is singular.
	at net.imglib2.realtransform.AffineTransform3D.invert(AffineTransform3D.java:362)
	at net.imglib2.realtransform.AffineTransform3D.set(AffineTransform3D.java:965)
	at bigwarp.BigWarpExporter.estimateAffineFromCorners(BigWarpExporter.java:676)
	at bdv.img.WarpedSource.estimateBoundingInterval(WarpedSource.java:123)
	at bdv.img.WarpedSource.getSource(WarpedSource.java:112)
	at bdv.util.source.alpha.AlphaSourceWarped.getSource(AlphaSourceWarped.java:47)
	at bdv.viewer.overlay.MultiBoxOverlayRenderer.setViewerState(MultiBoxOverlayRenderer.java:163)
	at bdv.viewer.ViewerPanel.drawOverlays(ViewerPanel.java:511)
```

This bug was mentioned in: https://github.com/saalfeldlab/bigwarp/issues/107, and since you changed how you were setting the transform it should not happen anymore, but here it is... 

It's a hard to catch error, I wonder if it's not a race condition with the viewer state. FYI bdv is not crashing so that's not so annoying (and I can remove the MultiBoxOverlayRenderer to avoid it).

**Comment by NicoKiaru** [comment]
I'm having this issue quite often now, and unfortunately, bdv is hanging.

It's called in 
```
Exception in thread "PainterThread" java.lang.RuntimeException: Matrix is singular.
	at net.imglib2.realtransform.AffineTransform3D.invert(AffineTransform3D.java:362)
	at net.imglib2.realtransform.AffineTransform3D.set(AffineTransform3D.java:965)
	at bigwarp.BigWarpExporter.estimateAffineFromCorners(BigWarpExporter.java:676)
	at bdv.img.WarpedSource.estimateBoundingInterval(WarpedSource.java:123)
	at bdv.img.WarpedSource.getSource(WarpedSource.java:112)
	at bdv.viewer.render.ProjectorFactory.getTransformedSource(ProjectorFactory.java:281)
	at bdv.viewer.render.ProjectorFactory.createSingleSourceVolatileProjector(ProjectorFactory.java:247)
	at bdv.viewer.render.ProjectorFactory.createSingleSourceProjector(ProjectorFactory.java:202)
	at bdv.viewer.render.ProjectorFactory.createProjector(ProjectorFactory.java:182)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:628)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:465)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:439)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:473)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
```

**Comment by NicoKiaru** [comment]
Hi @bogovicj, 

Do you think it's possible to make a release that simply catch this error ?

**Comment by tischi** [comment]
Hi @bogovicj and @NicoKiaru does that mean this is fixed?
Is there a released bigwarp version that we could depend on for this?

**Comment by bogovicj** [comment]
Thanks @tischi !
I'll cut a release soon and will ping you here once its out

**Comment by bogovicj** [comment]
Bigwarp 7.0.4 is released and fixes this 
@tischi 
@NicoKiaru
