### ISSUE TITLE
AffineModel2D fit error message

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#126]
I sometimes get this error message when warping 2D images:

```
mpicbg.models.IllDefinedDataPointsException: The set of data points is ill defined.  No Model could be solved.
	at mpicbg.models.AffineModel2D.fit(AffineModel2D.java:187)
	at bigwarp.BigWarp.fitBaselineWarpMagModel(BigWarp.java:1888)
	at bigwarp.BigWarp.setTransformationAll(BigWarp.java:2113)
	at bigwarp.BigWarp.access$500(BigWarp.java:149)
```

It's not a big deal because I can continue to work (it's not hanging), but maybe it's worth mentioning as an issue

**Comment by bogovicj** [comment]
Thanks @NicoKiaru ,
I'm pretty confident this error gets caught and bigwarp always(?) can proceed without side effects.

I think I'll add a short message to the bigwarp window and not dump the trace - would that be okay?

**Comment by NicoKiaru** [comment]
Yes that should be ok!
The error was always caught in my case.

Do you think it could be related to https://github.com/saalfeldlab/bigwarp/issues/124 ? I think there's an affine model used in the bounds estimation

**Comment by bogovicj** [comment]
> Do you think it could be related to #124 ? I think there's an affine model used in the bounds estimation

Good point, could be. Thanks for pointing that out, I'll make sure to investigate both of them at the same time.
