### ISSUE TITLE
Dataset without leading '/' yields error when exporting to zarr

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/bigwarp#130]
exporting to zarr using a dataset name without a leading slash yields:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.janelia.saalfeldlab.n5.zarr.N5ZarrWriter.createDataset(N5ZarrWriter.java:259)
	at org.janelia.saalfeldlab.n5.imglib2.N5Utils.save(N5Utils.java:1347)
	at bdv.ij.ApplyBigwarpPlugin.runN5Export(ApplyBigwarpPlugin.java:938)
	at bigwarp.BigWarp$2.run(BigWarp.java:1096)
```

**Comment by bogovicj** [comment]
This should be fixed given the next n5-zarr release 
https://github.com/saalfeldlab/n5-zarr/pull/9
