### ISSUE TITLE
Class not found - org/janelia/saalfeldlab/n5/universe/metadata/ome/ngff/v05/transformations/CoordinateTransform

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#168]
Hello!

I'm using BigWarp 9.1.2 in my IDE as a dependency in BigDataViewer-Playground  and I get this class not found error:

```
BigWarp version:9.1.2
Exception in thread "main" java.lang.NoClassDefFoundError: org/janelia/saalfeldlab/n5/universe/metadata/ome/ngff/v05/transformations/CoordinateTransform
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
	at java.lang.Class.getDeclaredMethod(Class.java:2156)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6224)
	at java.awt.Component.access$500(Component.java:186)
	at java.awt.Component$3.run(Component.java:6178)
	at java.awt.Component$3.run(Component.java:6176)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Component.checkCoalescing(Component.java:6175)
	at java.awt.Component.<init>(Component.java:6144)
	at java.awt.Container.<init>(Container.java:285)
	at javax.swing.JComponent.<init>(JComponent.java:588)
	at javax.swing.JPanel.<init>(JPanel.java:82)
	at javax.swing.JPanel.<init>(JPanel.java:95)
	at bdv.gui.TransformGraphPanel.<init>(TransformGraphPanel.java:70)
	at bigwarp.WarpVisFrame.<init>(WarpVisFrame.java:360)
	at bigwarp.BigWarp.<init>(BigWarp.java:562)
	at bigwarp.BigWarp.<init>(BigWarp.java:396)
	at sc.fiji.bdvpg.sourceandconverter.register.BigWarpLauncher.run(BigWarpLauncher.java:139)
	at sc.fiji.bdvpg.transform.BigWarpDemo2D.startBigWarp(BigWarpDemo2D.java:192)
	at sc.fiji.bdvpg.transform.BigWarpDemo2D.bigwarp(BigWarpDemo2D.java:92)
	at sc.fiji.bdvpg.transform.BigWarpDemo2D.main(BigWarpDemo2D.java:74)
Caused by: java.lang.ClassNotFoundException: org.janelia.saalfeldlab.n5.universe.metadata.ome.ngff.v05.transformations.CoordinateTransform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

Any idea what could be wrong ? Isn't this weird ? All n5 dependencies should be present because they are "transitive" dependencies present in BigWarp's pom file. (I'm using pom scijava 37.0.0)

**Comment by NicoKiaru** [comment]
Don't you need to replace:

https://github.com/saalfeldlab/bigwarp/blob/d38bc182bde56496ed396d04305c6bcd85cff484/pom.xml#L233-L236

by 
```
		<dependency>
			<groupId>org.janelia.saalfeldlab</groupId>
			<artifactId>n5</artifactId>
			<version>${n5.version}</artifactId>
		</dependency>
```

and this in all n5 dependencies ? Aren't your properties ignored otherwise ?

**Comment by NicoKiaru** [comment]
Ok, I can work by adding these props to my pom:

```
                <n5.version>3.2.0</n5.version>
		<n5-aws-s3.version>4.1.1</n5-aws-s3.version>
		<n5-blosc.version>1.1.1</n5-blosc.version>
		<n5-hdf5.version>2.2.0</n5-hdf5.version>
		<n5-google-cloud.version>4.1.0</n5-google-cloud.version>
		<n5-zarr.version>1.3.1</n5-zarr.version>
		<n5-universe.version>1.4.1</n5-universe.version>
		<n5-ij.version>4.1.0</n5-ij.version>
		<n5-viewer_fiji.version>6.1.0</n5-viewer_fiji.version>
```

not sure it's the right way since I have duplicated the versions, but I guess that'll be fine until this makes its way into pom scijava 8
