### ISSUE TITLE
PainterThread exception when closing bigwarp

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/bigwarp#25]
"I got an error message after closing the viewer. Before closing, I deleted two entries in the landmarks table without exporting." -Ala

```
Exception in thread "PainterThread" java.util.NoSuchElementException
    at java.util.ArrayDeque.removeFirst(ArrayDeque.java:280)
    at java.util.ArrayDeque.pop(ArrayDeque.java:517)
    at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:520)
    at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:416)
    at bdv.viewer.BigWarpViewerPanel.paint(BigWarpViewerPanel.java:201)
    at net.imglib2.ui.PainterThread.run(PainterThread.java:86)
```

**Comment by bogovicj** [comment]
Have not been able to reproduce.  May be a bigdataviewer issue.  Or may be a synchronization issue - i.e. window closes before repaint (tps recomputation) finishes.

**Comment by bogovicj** [comment]
Reproduced just now with Ala.  Does seem to be caused by window closing during transform recomputation.

**Comment by bogovicj** [comment]
Fixed by:
https://github.com/bigdataviewer/bigdataviewer-core/commit/f0115a373c2c8f45ae82d36d6d0c061f329dea97
See also:
https://github.com/bigdataviewer/bigdataviewer-core/issues/25
