### ISSUE TITLE
How to use standalone version

### ISSUE THREAD

**Issue by ToshinobuShimoi** [saalfeldlab/bigwarp#51]
Hi! I'm trying the exe version of bigwarp that you provide on conda, but not doing well. How do I pass arguments to that? I will appreciate it if you could give me some example. Thank you for your advice.

(I'm very new to Github and poor at English. I'm sorry If it's inappropriate to ask here.)

**Comment by bogovicj** [comment]
Hi @ToshinobuShimoi ,

This is a good place for your question.

I [updated the README](https://github.com/saalfeldlab/bigwarp/blob/master/README.md) that explicitly shows the arguments of the bigwarp conda executable.  You just need to give the path to the moving image and the path to the target image files.  

Note: Bigwarp uses [ImageJ](https://imagej.net/Welcome) to read the images, so if your image files are not readable my imageJ, then they won't be readable by bigwarp.

Please post back if you're still having trouble.

**Comment by ToshinobuShimoi** [comment]
Hi John,

Thank you very much for your helpful quick response, but unfortunately Apply_Bigwarp_Xfm.groovy and  other two scripts don't work on my Fiji. The error messages are as follows,


[ERROR] null
groovy.lang.MissingMethodException: No signature of method: static bdv.ij.ApplyBigwarpPlugin.apply() is applicable for argument types: (ij.ImagePlus, ij.ImagePlus, bigwarp.landmarks.LandmarkTableModel, java.lang.String, java.lang.String, java.lang.String, null, null, null, bdv.viewer.Interpolation, java.lang.Boolean, java.lang.Integer) values: [img["test.tif" (-4), 8-bit, 1872x6344x1x1x1], img["SB.tif" (-5), 24-bit, 211x627x1x1x1], ...]
Possible solutions: any()
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1506)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1492)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at Script1.run(Script1.groovy:38)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:303)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:122)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


What should I do here? I'm sorry to bother you again.

Toby
