### ISSUE TITLE
array out of bounds during landmark placement 

### ISSUE THREAD

**Issue by bercowskya** [saalfeldlab/bigwarp#63]
WARNING:
Opening <SpimData> dataset that is not suited for interactive browsing.
Consider resaving as HDF5 for better performance.
WARNING:
Opening <SpimData> dataset that is not suited for interactive browsing.
Consider resaving as HDF5 for better performance.
Exception in thread "Thread-5" java.lang.ArrayIndexOutOfBoundsException: -1
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.initialGuessAtInverse(ThinPlateR2LogRSplineKernelTransform.java:825)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.inverse(ThinPlateR2LogRSplineKernelTransform.java:917)
	at bigwarp.landmarks.LandmarkTableModel.computeWarpedPoint(LandmarkTableModel.java:745)
	at bigwarp.landmarks.LandmarkTableModel.updateAllWarpedPoints(LandmarkTableModel.java:716)
	at bigwarp.BigWarp$SolveThread.run(BigWarp.java:2733)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.initialGuessAtInverse(ThinPlateR2LogRSplineKernelTransform.java:825)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.inverse(ThinPlateR2LogRSplineKernelTransform.java:917)
	at bigwarp.landmarks.LandmarkTableModel.computeWarpedPoint(LandmarkTableModel.java:745)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:687)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:583)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:578)
	at bigwarp.BigWarp.addPoint(BigWarp.java:1223)
	at bigwarp.BigWarp$MouseLandmarkListener.mouseReleased(BigWarp.java:2392)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.initialGuessAtInverse(ThinPlateR2LogRSplineKernelTransform.java:825)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.inverse(ThinPlateR2LogRSplineKernelTransform.java:917)
	at bigwarp.landmarks.LandmarkTableModel.computeWarpedPoint(LandmarkTableModel.java:745)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:687)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:583)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:578)
	at bigwarp.BigWarp.addPoint(BigWarp.java:1223)
	at bigwarp.BigWarp$MouseLandmarkListener.mouseReleased(BigWarp.java:2392)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.initialGuessAtInverse(ThinPlateR2LogRSplineKernelTransform.java:825)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.inverse(ThinPlateR2LogRSplineKernelTransform.java:917)
	at bigwarp.landmarks.LandmarkTableModel.computeWarpedPoint(LandmarkTableModel.java:745)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:687)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:583)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:578)
	at bigwarp.BigWarp.addPoint(BigWarp.java:1223)
	at bigwarp.BigWarp$MouseLandmarkListener.mouseReleased(BigWarp.java:2392)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.initialGuessAtInverse(ThinPlateR2LogRSplineKernelTransform.java:825)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.inverse(ThinPlateR2LogRSplineKernelTransform.java:917)
	at bigwarp.landmarks.LandmarkTableModel.computeWarpedPoint(LandmarkTableModel.java:745)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:687)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:583)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:578)
	at bigwarp.BigWarp.addPoint(BigWarp.java:1223)
	at bigwarp.BigWarp$MouseLandmarkListener.mouseReleased(BigWarp.java:2392)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by bogovicj** [comment]
Thanks, nice find.

To reproduce this:
1) Add two points in the moving image
2) Manually activate them by clicking in the landmark table
3) Make sure no rows in the table are selected
4) Add two points in the target image (observe that they are not paired to the moving points)
5) Manually activate the two unpaired target image points
