### ISSUE TITLE
Error when clicking to add a landmark in 2D registration

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#91]
with the current version (5.1.1-SNAPSHOT in maven scijava, but I don't know the commit), I experienced very often a bug during 2D registration of multiresolution SourceAndConverter (I don't know if these details are important). Sometimes, just by adding a point in landmark mode, I get these errors : (I'm putting 2 stack traces because the one from the ImageJ window and the one from the IDE looks different):

ImageJ stack trace:

```

[WARNING] Ignoring unsupported output: cr_out [ch.epfl.biop.java.utilities.roi.ConvertibleRois]
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.realtransform.Wrapped2DTransformAs3D.apply(Wrapped2DTransformAs3D.java:31)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:649)
	at bigwarp.BigWarp.addPoint(BigWarp.java:1742)
	at bigwarp.BigWarp$MouseLandmarkListener.mouseReleased(BigWarp.java:3001)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.realtransform.Wrapped2DTransformAs3D.apply(Wrapped2DTransformAs3D.java:31)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:649)
	at bigwarp.BigWarp.addPoint(BigWarp.java:1742)
	at bigwarp.BigWarp$MouseLandmarkListener.mouseReleased(BigWarp.java:3001)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ch.epfl.biop.java.utilities.roi.ConvertibleRois
Found -> ch.epfl.biop.java.utilities.roi.types.IJShapeRoiArray State
NR Converting:ch.epfl.biop.java.utilities.roi.types.IJShapeRoiArray->ch.epfl.biop.java.utilities.roi.types.RealPointList
[ERROR] Module threw exception
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at net.imglib2.realtransform.inverse.InverseRealTransformGradientDescent.apply(InverseRealTransformGradientDescent.java:204)
	at net.imglib2.realtransform.inverse.WrappedIterativeInvertibleRealTransform.applyInverse(WrappedIterativeInvertibleRealTransform.java:79)
	at net.imglib2.realtransform.Wrapped2DTransformAs3D.applyInverse(Wrapped2DTransformAs3D.java:44)
	at net.imglib2.realtransform.InvertibleRealTransformSequence.applyInverse(InvertibleRealTransformSequence.java:102)
	at ch.epfl.biop.registration.sourceandconverter.SacBigWarp2DRegistration.getPtsRegistration(SacBigWarp2DRegistration.java:199)
	at ch.epfl.biop.atlastoimg2d.AtlasToSourceAndConverter2D.computeTransformedRois(AtlasToSourceAndConverter2D.java:227)
	at ch.epfl.biop.atlastoimg2d.AtlasToSourceAndConverter2D.addRegistration(AtlasToSourceAndConverter2D.java:146)
	at ch.epfl.biop.atlastoimg2d.commands.sourceandconverter.SacImageToAtlasRegister.run(SacImageToAtlasRegister.java:81)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ch.epfl.biop.atlastoimg2d.commands.sourceandconverter.SacImageToAtlasWizard.run(SacImageToAtlasWizard.java:56)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at net.imglib2.realtransform.inverse.InverseRealTransformGradientDescent.apply(InverseRealTransformGradientDescent.java:204)
	at net.imglib2.realtransform.inverse.WrappedIterativeInvertibleRealTransform.applyInverse(WrappedIterativeInvertibleRealTransform.java:79)
	at net.imglib2.realtransform.Wrapped2DTransformAs3D.applyInverse(Wrapped2DTransformAs3D.java:44)
	at net.imglib2.realtransform.InvertibleRealTransformSequence.applyInverse(InvertibleRealTransformSequence.java:102)
	at ch.epfl.biop.registration.sourceandconverter.SacBigWarp2DRegistration.getPtsRegistration(SacBigWarp2DRegistration.java:199)
	at ch.epfl.biop.atlastoimg2d.AtlasToSourceAndConverter2D.computeTransformedRois(AtlasToSourceAndConverter2D.java:227)
	at ch.epfl.biop.atlastoimg2d.AtlasToSourceAndConverter2D.addRegistration(AtlasToSourceAndConverter2D.java:146)
	at ch.epfl.biop.atlastoimg2d.commands.sourceandconverter.SacImageToAtlasRegister.run(SacImageToAtlasRegister.java:81)
	... 9 more
```

IntelliJ stack trace:

```

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.realtransform.Wrapped2DTransformAs3D.apply(Wrapped2DTransformAs3D.java:31)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:649)
	at bigwarp.BigWarp.addPoint(BigWarp.java:1742)
	at bigwarp.BigWarp$MouseLandmarkListener.mouseReleased(BigWarp.java:3001)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.realtransform.Wrapped2DTransformAs3D.apply(Wrapped2DTransformAs3D.java:31)
	at bigwarp.landmarks.LandmarkTableModel.pointEdit(LandmarkTableModel.java:649)
	at bigwarp.BigWarp.addPoint(BigWarp.java:1742)
	at bigwarp.BigWarp$MouseLandmarkListener.mouseReleased(BigWarp.java:3001)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by NicoKiaru** [comment]
Unfortunately I still have this issue in the version

`BigWarp hash:5.1.1-SNAPSHOT-280bd0488fb390be521bd0595d3f801b4e56870a`

**Comment by NicoKiaru** [comment]
I do not have time to dig now, but I'll try to make a minimal example.

**Comment by NicoKiaru** [comment]
Also, I use these explicit versions for now:

```

		<imglib2.version>5.9.0</imglib2.version>
		<imglib2-ij.version>2.0.0-beta-46</imglib2-ij.version>
		<bigdataviewer-core.version>9.0.1</bigdataviewer-core.version>
		<bigdataviewer-vistools.version>1.0.0-beta-20</bigdataviewer-vistools.version>
		<spim_data.version>2.2.4</spim_data.version>
		<ui-behaviour.version>2.0.1</ui-behaviour.version>
		<bigwarp_fiji.version>5.1.1-SNAPSHOT</bigwarp_fiji.version>

		<scijava-ui-swing.version>0.13.0</scijava-ui-swing.version>
```

**Comment by bogovicj** [comment]
Thanks!

**Comment by NicoKiaru** [comment]
So, to reproduce it 'easily':

Use the macro below...
```
run("Big Warp XML/HDF5", "fixedimagexml=thecorrectpath\\projornot.xml movingimagexml=thecorrectpath\\projornot.xml");
```
... with the dataset below (that has a stupid name), which is just a 2d xml/hdf5 dataset
[projornot.zip](https://github.com/saalfeldlab/bigwarp/files/4582286/projornot.zip)

After, just put 4 landmarks in both the moving and fixed bdv windows, press T to trigger the transformation. Now you can put a 5th point into the right window, but when you add the corresponding location of the 5th point in the left window, the error is triggered, in my hands, all the time.

**Comment by NicoKiaru** [comment]
Just FYI, I still have the issue in commit

`BigWarp hash:5.1.1-SNAPSHOT-c1743b6e0de13f978448d88de817649537eabced`

**Comment by bogovicj** [comment]
Awesome, I'm getting that exception, thanks so much.  I'm on it.

**Comment by bogovicj** [comment]
@NicoKiaru  I think https://github.com/saalfeldlab/bigwarp/commit/62a14af723242ce91d93789547d4499cb2baa6a0 fixes this

**Comment by NicoKiaru** [comment]
I have a NullPointer on the first landmark placement, but maybe it's because of the way I initialize BigWarp:
```

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at bigwarp.BigWarp.addPoint(BigWarp.java:1710)
	at bigwarp.BigWarp$MouseLandmarkListener.mouseReleased(BigWarp.java:2974)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

BigWarp hash:5.1.1-SNAPSHOT-62a14af723242ce91d93789547d4499cb2baa6a0

**Comment by bogovicj** [comment]
The newest build may address this, but I didnt try hard to reproduce since you said you're initializing bigwarp yourself.  If it's still broken, I'll work harder to create the issue.

Thanks as always!

**Comment by NicoKiaru** [comment]
BigWarp hash:5.1.1-SNAPSHOT-4a3dbfe50319ffcc3407f1cf1b1d74fb73fc3065 👏 👏 

No more issues on this side! Thanks for fixing!
